version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lwf_app
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./package*.json:/app/package*.json
    environment:
      NODE_ENV: development
    command: npm run
